<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FireWill.Core\FireWill.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\assets\backgrounds\susanoo-madara.mp4"
                      LogicalName="FireWill.Assets.Backgrounds.susanoo-madara.mp4" />
    <EmbeddedResource Include="..\..\assets\backgrounds\flowing-sasuke.mp4"
                      LogicalName="FireWill.Assets.Backgrounds.flowing-sasuke.mp4" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>Fire Will</AssemblyName>
    <RootNamespace>FireWill.App</RootNamespace>
    <Product>Fire Will</Product>
    <Version>0.1.9</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\..\assets\app\FireWill.ico</ApplicationIcon>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

</Project>
